[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Telecommunications: Investigating the Applications and Impacts of Intelligent Technologies in the Telecom Industry"
